import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/footer";
import Header from "../components/header";
import Nominate from "../components/nominate";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col min-h-screen bg-black">
      <Head>
        <title>TEDxYCCE 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex-1">
        {/* <h1 className="text-2xl text-white">Welcome</h1> */}
        <Nominate />
      </main>
      <Footer />
    </div>
  );
};

export default Home;
