import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/footer";
import Header from "../components/header";

const Home: NextPage = () => {
  return (
    <div className="bg-black min-h-screen flex flex-col">
      <Head>
        <title>TEDxYCCE 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex-1">
        <h1 className="text-2xl">Welcome</h1>
      </main>
      <Footer />
    </div>
  );
};

export default Home;
